name: nightly update
on:
  # Allow manual triggers.
  workflow_dispatch: {}
  # Run once a day.
  schedule:
    - cron: "0 1 * * *"

jobs:
  create-pr:
    strategy:
      matrix:
        kernel:
          - '4.19'
          - '5.4'
          - '5.10'
          - '5.15'
          - '6.1'
          - '6.6'
          - 'bpf-next'
          - 'rhel8'
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: commit
        id: commit
        run: |
          id=$(date +%Y%m%d.%H%M%S)
          git switch -c pr/${{ matrix.kernel }}-${id}
          git config user.name "GH action"
          git config user.email "ghabot@does.not.exist.cilium.org"
          echo "${{ matrix.kernel }} $id" > misc/dummy
          git add misc/dummy
          git commit -a -m "${{ matrix.kernel }}: $id"
          git show HEAD
          git push --set-upstream origin pr/${{ matrix.kernel }}-${id}
          echo "id=$id" | tee -a $GITHUB_OUTPUT
      - name: push PR
        env:
          GH_TOKEN: ${{ secrets.LVH_GITHUB_TOKEN }}
        run: |
          id=${{ steps.commit.outputs.id }}
          gh pr create \
            -l "gha-builds/kernel/${{ matrix.kernel }}" \
            --title "${{ matrix.kernel }} update: $id" \
            --body "PR to update ${{ matrix.kernel }}" \
