name: Validate renovate configuration

on:
  pull_request:
    paths:
      - '.github/renovate.json5'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout configuration
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      # this step uses latest renovate slim release
      - name: Validate configuration
        run: >
          docker run --rm --entrypoint "renovate-config-validator"
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5"
          renovate/renovate:slim "/renovate.json5"
