name: Validate renovate configuration

on:
  pull_request:
    paths:
      - '.github/renovate.json5'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout configuration
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      # this step uses latest renovate slim release
      - name: Validate configuration
        run: >
          docker run --rm --entrypoint "renovate-config-validator"
          -v "${{ github.workspace }}/.github/renovate.json5":"/renovate.json5"
          renovate/renovate:slim "/renovate.json5"
